### ISSUE TITLE
Fails to deserialize a top-level vector.

### ISSUE THREAD

**Issue by vi** [toml-rs/toml-rs#303] opened 2019-04-18 17:37 UTC
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bcf3a5fe519cf84e3edefa4e0edfbc57

```rust
extern crate toml; // 0.5.0
extern crate serde_derive; // 1.0.90

use serde_derive::{Serialize,Deserialize};

#[derive(Serialize,Deserialize)]
struct Qqq {
    
}

fn main() {
    let q = vec![Qqq{}];
    let s = toml::to_string(&q).unwrap();
    eprintln!("{}", s);
    let _ : Vec<Qqq> = toml::from_slice(s.as_bytes()).unwrap();
}
```

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 1.22s
     Running `target/debug/playground`
[[]]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Wanted { expected: "a table key", found: "a right bracket" }, line: Some(0), col: 2, message: "", key: [] } }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Also fails if the struct is not empty.

**Comment by ehuss** [comment] 2019-04-18 21:45
I think the issue is that the deserializer does not support raw toml values, it only supports full toml documents (see https://github.com/alexcrichton/toml-rs/issues/194#issuecomment-313138743). Thus you need a map:

```rust
    let mut q = HashMap::new();
    q.insert("foo", vec![Qqq{}]);
    let s = toml::to_string(&q).unwrap();
    eprintln!("{}", s);
    let _ : HashMap<String, Vec<Qqq>> = toml::from_slice(s.as_bytes()).unwrap();
```

I have a branch that partially exposes parsing of raw values, but it's part of a larger project that I haven't finished.

**Comment by epage** [comment] 2022-09-23 17:13
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.

**Closed by epage** 2022-09-23 17:13 UTC
Labels: enhancement, A-parsing
