### ISSUE TITLE
Update to v1.0.0-rc.1

### ISSUE THREAD

**Issue by pyfisch** [toml-rs/toml-rs#392] opened 2020-05-14 16:04 UTC
On April 1 a new version of TOML was published: https://github.com/toml-lang/toml/blob/master/CHANGELOG.md#100-rc1--2020-04-01

The changelog mentions the following changes:

* [x] Clarify in ABNF how quotes in multi-line basic and multi-line literal strings are allowed to be used. (PR in #393)
* [x] Leading zeroes in exponent parts of floats are permitted.
* [x] Clarify that control characters are not permitted in comments.
* [ ] Clarify behavior of tables defined implicitly by dotted keys.
  * [x] spec text:
    > Dotted keys define everything to the left of each dot as a table. Since tables cannot be defined more than once, redefining such tables using a `[table]` header is not allowed. Likewise, using dotted keys to redefine tables already defined in `[table]` form is not allowed.
  * [ ] spec text ([example file][4]):
    > The `[table]` form can, however, be used to define sub-tables within tables defined via dotted keys.
* [x] Clarify that inline tables are immutable.
* [x] Clarify that trailing commas are not allowed in inline tables.
* [x] Clarify in ABNF that UTF-16 surrogate code points (U+D800 - U+DFFF) are not allowed in strings or comments. (*ensured by Rust*)
 * [x] Allow raw tab characters in basic strings and multi-line basic strings.
 * [x] Allow heterogenous values in arrays. (was changed in #358)

TOML is getting [official compliance tests][1]. The repository contains no actual tests yet but a script to run the compliance tests eventually. I think the best way to reach v1.0 and to avoid bugs is to use the test suite to check both deserialization and serialization.

While this crate already contains a test runner for an almost identical format it may be good to interface with the default Python test runner. If many implementations use the default runner it becomes easy to monitor the correctness of many different implementations.

* [ ] Write script implementing the [decoder interface][2] (*a serializer for the JSON format already exists*) <https://github.com/alexcrichton/toml-rs/blob/7a43ac9e9c28afec8414f6d924024f5d33fe8fa2/test-suite/tests/valid.rs#L9-L54>
* [ ] Write script implementing the [encoder interface][3]
* [ ] **Optional**: Remove rust test runner (upside: less code, downside: Python is needed to test this crate)

Additionally this is a good opportunity to split the `Datetime` as suggested in <https://github.com/alexcrichton/toml-rs/issues/159#issuecomment-463732912> by @quadrupleslap. The TOML spec and tests make it very clear that these are indeed distinct types. I think it will be easier to use those values if one can be sure that a table contains the correct kind of date or time and does not have to check the value.

The four new types each has a corresponding chrono type:

* `DateTime` ⟷ `chrono::DateTime`
* `LocalDateTime` ⟷ `chrono::NaiveDateTime`
* `LocalDate` ⟷ `chrono::NaiveDate`
* `LocalTime` ⟷ `chrono::NaiveTime`

The TOML types can be converted with `try_from` to chrono types. An error is returned if the date does not exist (e. g. *2019-02-29*). In the other direction `from` is used as no error can occur.

* [ ] Split `Datetime`
* [ ] Implement conversions to chrono types
* [ ] Implement conversions from chrono types

[1]: https://github.com/toml-lang/compliance
[2]: https://github.com/toml-lang/compliance/blob/master/docs/interfaces.md#decoders
[3]: https://github.com/toml-lang/compliance/blob/master/docs/interfaces.md#encoders
[4]: https://gist.github.com/pyfisch/a6d648df122efc27a0fb51041680abfa#file-table-dotted-toml

**Comment by ChristopherRabotin** [comment] 2020-05-21 05:29
It's a release candidate: shouldn't this library work only with confirmed releases?

**Comment by alexcrichton** [comment] 2020-05-22 16:55
Given the stability of TOML over time I think it's fine to go ahead and update to the current release candidate, since the actual release is likely to be compatible with the candidate. I unfortunately don't have a ton of time to do this nowadays :(

**Comment by pyfisch** [comment] 2020-05-24 16:13
I've updated the initial comment with information about the necessary changes.

Most items from the changelog for v1.00-rc.1 were already implemented in this crate. I checked each item and found just two were the TOML decoder needs to be changed.

Do you agree to provide a test interface?
What do you think about splitting the date and time types?

**Comment by alexcrichton** [comment] 2020-05-27 14:48
Hm I'm not sure what you mean by test interface? As for date/time types, if the upstream spec is changing makes sense to follow it! (I haven't followed upstream very closely myself)

**Comment by pyfisch** [comment] 2020-05-27 18:28
> Hm I'm not sure what you mean by test interface?

I am referring to this document: <https://github.com/toml-lang/compliance/blob/master/docs/interfaces.md>
It describes a decoder that reads a TOML document from `stdin` and writes a special JSON representation of the same document to `stdout`.

**Comment by ehuss** [comment] 2020-05-28 17:19
I wouldn't be opposed to adding the encoder/decoder interface, but I'm uncertain how it would be structured so the code can be shared with the test suite.  What would be the value of including this interface if this library already includes its own testsuite, though?

**Comment by pyfisch** [comment] 2020-05-28 17:58
> What would be the value of including this interface if this library already includes its own testsuite, though?

The benefit is if many libraries implement this interface it becomes easier to test, fuzz and compare the libraries. For example one could randomly generate documents and see if one of them crashes a TOML library. Or they put the same random documents into multiple different implementations and compare if the output of all implementations is the same.
With these tools more bugs and inconsistencies in implementations can be found and resolved e.g. by updating the compliance test suite.
Of course you can also argue that TOML is simple enough and that this crate is very unlikely to contain bugs and therefore does not need this interface.

**Comment by ScottAwesome** [comment] 2021-02-11 17:11
For what it's worth, the full v1 spec is final now:

https://toml.io/en/v1.0.0

https://github.com/toml-lang/toml/blob/master/CHANGELOG.md#100--2021-01-11

I don't know if this changes plans outright. I'd like to see support for v1.0.0

**Comment by xpe** [comment] 2021-08-29 15:24
> The TOML types can be converted with try_from to chrono types.

With regards to conversions between `DateTime` and `chrono`, as part of making `DateTime` fields public, we now [have more field-level documentation](https://github.com/alexcrichton/toml-rs/pull/439/commits/61663b99db73a7dbaaedb0d01c2d44fe7c38be43) that might be useful.

I also made a different PR (#443) that I closed because it wasn't going in the best direction, but perhaps there may be [some useful code](https://github.com/xpe/toml-rs/commit/5b3771ecd79efc4036767508e8bce8b99f9ab21e#diff-dea6b5915f4569219169086434bf0bf034579033e1bef4d94529210fd1ee73d7R97-R147) to borrow. For example:

```rs
    /// Is this a TOML Offset Date-Time?
    ///
    /// | date      | time      | offset    | kind             |
    /// | --------- | --------- | --------- | ---------------- |
    /// | `Some(_)` | `Some(_)` | `Some()`  | Offset Date-Time |
    pub fn is_offset_datetime(&self) -> bool {
        self.date.is_some() && self.time.is_some() && self.offset.is_some()
    }

    /// Is this a TOML Local Date-Time?
    ///
    /// | date      | time      | offset    | kind             |
    /// | --------- | --------- | --------- | ---------------- |
    /// | `Some(_)` | `Some(_)` | `None`    | Local Date-Time  |
    pub fn is_local_datetime(&self) -> bool {
        self.date.is_some() && self.time.is_some() && self.offset.is_none()
    }

    /// Is this a TOML Local Date?
    ///
    /// | date      | time      | offset    | kind             |
    /// | --------- | --------- | --------- | ---------------- |
    /// | `Some(_)` | `None`    | `None`    | Local Date       |
    pub fn is_local_date(&self) -> bool {
        self.date.is_some() && self.time.is_none() && self.offset.is_none()
    }

    /// Is this a TOML Local Time?
    ///
    /// | date      | time      | offset    | kind             |
    /// | --------- | --------- | --------- | ---------------- |
    /// | `None`    | `Some(_)` | `None`    | Local Time       |
    pub fn is_local_time(&self) -> bool {
        self.date.is_none() && self.time.is_some() && self.offset.is_none()
    }

    /// Is this invalid?
    ///
    /// | date      | time      | offset    | kind             |
    /// | --------- | --------- | --------- | ---------------- |
    /// | `None`    | `None`    | `None`    | *invalid*        |
    /// | `None`    | `None`    | `Some(_)` | *invalid*        |
    /// | `None`    | `Some(_)` | `Some(_)` | *invalid*        |
    /// | `Some(_)` | `None`    | `Some(_)` | *invalid*        |
    pub fn is_invalid(&self) -> bool {
        (self.date.is_none() && self.time.is_none())
            || (self.date.is_none() && self.offset.is_some())
            || (self.time.is_none() && self.offset.is_some())
    }
```

**Comment by gitpicard** [comment] 2022-02-28 01:19
What is the status on updating to the latest spec?

**Comment by epage** [comment] 2022-09-23 17:11
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.

**Closed by epage** 2022-09-23 17:11 UTC
